import json
import math
import os
from collections import deque

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


DEFAULT_LID_LIMIT_Z = 0.164
DEFAULT_LID_LIMIT_Y = 0.114


def normalize_angle_deg(angle_deg):
    return float(angle_deg) % 360.0


def expand_line_rays(line):
    """Return the rays (y0, z0, dy, dz) generated by one line definition.

    The angle is measured from the +Z axis (vertical axis of the (Y, Z) plane)
    towards +Y. "Symmetry Y" (XY plane) mirrors across the Y axis (Z -> -Z) and
    "Symmetry Z" (XZ plane) mirrors across the Z axis (Y -> -Y).
    """
    if not isinstance(line, dict):
        return []

    y0 = float(line.get("y_step", 0.0))
    z0 = float(line.get("z_step", 0.0))
    theta = math.radians(normalize_angle_deg(line.get("angle_deg", 0.0)))
    dy = math.sin(theta)
    dz = math.cos(theta)

    rays = [(y0, z0, dy, dz)]
    if line.get("symmetry_y", False):
        rays.append((y0, -z0, dy, -dz))
    if line.get("symmetry_z", False):
        rays.append((-y0, z0, -dy, dz))
    if line.get("symmetry_y", False) and line.get("symmetry_z", False):
        rays.append((-y0, -z0, -dy, -dz))

    unique = {}
    for ray in rays:
        unique[tuple(round(value, 12) + 0.0 for value in ray)] = ray
    return list(unique.values())


def build_rays(lines):
    rays = []
    for line in lines or []:
        rays.extend(expand_line_rays(line))
    return rays


def compute_plot_half_extent(y, z, rays=(), margin=0.1):
    """Half side of the square, origin-centered window containing data and ray anchors."""
    values = [0.0]
    values.extend(np.abs(np.asarray(y, dtype=float)).ravel().tolist())
    values.extend(np.abs(np.asarray(z, dtype=float)).ravel().tolist())
    for y0, z0, _, _ in rays:
        values.extend([abs(y0), abs(z0)])
    half = max(values) * (1.0 + margin)
    return half if half > 0 else 1.0


def _flood_label(blocked, min_pixels=30):
    """Label 4-connected free pixels; blocked pixels take the label of their nearest free neighbour.

    Components smaller than min_pixels are rasterization pockets (e.g. where several rays meet
    at the origin) and are absorbed by their neighbours instead of counting as regions.
    """
    n = blocked.shape[0]
    flat_blocked = blocked.ravel().tolist()
    labels = [0] * (n * n)
    count = 0

    for start in range(n * n):
        if flat_blocked[start] or labels[start]:
            continue
        count += 1
        labels[start] = count
        stack = [start]
        while stack:
            p = stack.pop()
            r, c = divmod(p, n)
            for q, ok in ((p - n, r > 0), (p + n, r < n - 1), (p - 1, c > 0), (p + 1, c < n - 1)):
                if ok and not flat_blocked[q] and not labels[q]:
                    labels[q] = count
                    stack.append(q)

    sizes = np.bincount(labels, minlength=count + 1)
    keep = [label for label in range(1, count + 1) if sizes[label] >= min_pixels]
    remap = [0] * (count + 1)
    for new_label, old_label in enumerate(keep, start=1):
        remap[old_label] = new_label
    labels = [remap[label] for label in labels]
    count = len(keep)
    if count == 0:
        return np.ones((n, n), dtype=int), 1

    queue = deque(i for i in range(n * n) if labels[i])
    while queue:
        p = queue.popleft()
        r, c = divmod(p, n)
        for q, ok in ((p - n, r > 0), (p + n, r < n - 1), (p - 1, c > 0), (p + 1, c < n - 1)):
            if ok and not labels[q]:
                labels[q] = labels[p]
                queue.append(q)

    return np.asarray(labels, dtype=int).reshape(n, n), count


def build_region_grid(rays, half, resolution=400):
    """Rasterize the (Y, Z) window [-half, half]^2 and label the regions cut by the rays.

    Each ray is also joined to the origin by an auxiliary segment, so rays that do not
    cross still split the plane into sectors around the origin.

    Returns (grid, n_regions); grid[row, col] with row -> Z and col -> Y, region ids in 1..n,
    ordered clockwise from the +Z axis by region centroid.
    """
    if not rays:
        return np.ones((resolution, resolution), dtype=int), 1

    pixel = 2.0 * half / resolution
    blocked = np.zeros((resolution, resolution), dtype=bool)
    t = np.arange(0.0, 6.0 * half, pixel / 2.0)

    for y0, z0, dy, dz in rays:
        cols = np.floor((y0 + t * dy + half) / pixel).astype(int)
        rows = np.floor((z0 + t * dz + half) / pixel).astype(int)
        inside = (cols >= 0) & (cols < resolution) & (rows >= 0) & (rows < resolution)
        blocked[rows[inside], cols[inside]] = True

        reach = math.hypot(y0, z0)
        if reach > 0:
            s = np.arange(0.0, reach, pixel / 2.0)
            cols = np.floor((s * y0 / reach + half) / pixel).astype(int)
            rows = np.floor((s * z0 / reach + half) / pixel).astype(int)
            blocked[np.clip(rows, 0, resolution - 1), np.clip(cols, 0, resolution - 1)] = True

    grid, count = _flood_label(blocked)

    rows_idx, cols_idx = np.indices(grid.shape)
    centers_y = (cols_idx + 0.5) * pixel - half
    centers_z = (rows_idx + 0.5) * pixel - half
    sizes = np.bincount(grid.ravel(), minlength=count + 1)[1:].astype(float)
    mean_y = np.bincount(grid.ravel(), weights=centers_y.ravel(), minlength=count + 1)[1:] / sizes
    mean_z = np.bincount(grid.ravel(), weights=centers_z.ravel(), minlength=count + 1)[1:] / sizes
    angles = np.mod(np.degrees(np.arctan2(mean_y, mean_z)), 360.0)
    order = np.argsort(angles, kind="stable")
    remap = np.zeros(count + 1, dtype=int)
    remap[order + 1] = np.arange(1, count + 1)
    return remap[grid], count


def _lookup_regions(grid, y, z, half):
    n = grid.shape[0]
    pixel = 2.0 * half / n
    cols = np.clip(np.floor((np.asarray(y, dtype=float) + half) / pixel).astype(int), 0, n - 1)
    rows = np.clip(np.floor((np.asarray(z, dtype=float) + half) / pixel).astype(int), 0, n - 1)
    return grid[rows, cols]


def classify_custom_lids(y, z, rays, half=None):
    """Assign each (y, z) point to a region label "Lid k" defined by the rays."""
    y = np.asarray(y, dtype=float)
    z = np.asarray(z, dtype=float)
    if half is None:
        half = compute_plot_half_extent(y, z, rays)
    grid, _ = build_region_grid(rays, half)
    ids = _lookup_regions(grid, y, z, half)
    return np.asarray([f"Lid {idx}" for idx in ids], dtype=object)


def build_custom_lid_config_path(base_folder):
    return os.path.join(base_folder, "custom_lids_config.json")


def load_custom_lid_config(config_path):
    if not config_path or not os.path.exists(config_path):
        return []

    try:
        with open(config_path, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, ValueError):
        return []

    if isinstance(payload, dict):
        payload = payload.get("lines", [])

    if not isinstance(payload, list):
        return []

    cleaned = []
    for item in payload:
        if not isinstance(item, dict):
            continue
        cleaned.append({
            "y_step": float(item.get("y_step", 0.0)),
            "z_step": float(item.get("z_step", 0.0)),
            "angle_deg": float(item.get("angle_deg", 0.0)),
            "symmetry_y": bool(item.get("symmetry_y", item.get("symmetry_horizontal", False))),
            "symmetry_z": bool(item.get("symmetry_z", item.get("symmetry_vertical", False))),
        })

    return cleaned


def save_custom_lid_config(config_path, lines):
    with open(config_path, "w", encoding="utf-8") as handle:
        json.dump({"lines": lines}, handle, indent=2, ensure_ascii=False)


def _iter_step_folders(base_folder):
    step_folders = []

    if not os.path.isdir(base_folder):
        return step_folders

    for entry in sorted(os.listdir(base_folder)):
        path = os.path.join(base_folder, entry)
        if os.path.isdir(path) and entry.startswith("Step"):
            step_folders.append(path)

    def sort_key(folder):
        match = __import__("re").search(r"Step(\d+)", os.path.basename(folder))
        return int(match.group(1)) if match else -1

    return sorted(step_folders, key=sort_key)


def _read_force_data(step_folder):
    input_path = os.path.join(step_folder, "Fuerzas.txt")
    if not os.path.exists(input_path):
        return None

    data = np.loadtxt(input_path, skiprows=1)
    if data.ndim == 1:
        data = data.reshape(1, -1)

    Fx = data[:, 1]
    Fy = data[:, 2]
    Fz = data[:, 3]
    Tx = data[:, 4]
    Ty = data[:, 5]
    Tz = data[:, 6]
    x = data[:, 7]
    y = data[:, 8]
    z = data[:, 9]

    return {
        "Fx": Fx,
        "Fy": Fy,
        "Fz": Fz,
        "Tx": Tx,
        "Ty": Ty,
        "Tz": Tz,
        "x": x,
        "y": y,
        "z": z,
        "data": data,
    }


def _format_table_row(row_values):
    return "\t".join(str(value) for value in row_values)


def _plot_variable_by_lids(x, y, labels, save_path, title):
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_aspect("equal")
    ax.grid(True, alpha=0.2)
    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_title(title)

    unique_labels = sorted({label for label in labels})
    colors = plt.cm.tab20(np.linspace(0, 1, max(len(unique_labels), 1)))
    color_map = {label: colors[i] for i, label in enumerate(unique_labels)}

    for label in unique_labels:
        mask = labels == label
        ax.scatter(x[mask], y[mask], s=70, color=color_map[label], label=label, alpha=0.9)

    # add a central reference at the origin
    ax.scatter([0.0], [0.0], s=60, color="black", marker="x")

    ax.legend(title="Lids", loc="upper right")
    fig.tight_layout()
    fig.savefig(save_path, dpi=200, bbox_inches="tight")
    plt.close(fig)


def _draw_yz_frame(ax, half, title):
    ax.set_xlim(-half, half)
    ax.set_ylim(-half, half)
    ax.set_aspect("equal", adjustable="box")
    ax.axhline(0.0, color="dimgray", linewidth=1.2, zorder=1)
    ax.axvline(0.0, color="dimgray", linewidth=1.2, zorder=1)
    ax.grid(True, alpha=0.2)
    ax.set_xlabel("Y [m]")
    ax.set_ylabel("Z [m]")
    ax.set_title(title)


def _draw_rays(ax, rays, half):
    length = 6.0 * half
    for y0, z0, dy, dz in rays:
        ax.plot([y0, y0 + length * dy], [z0, z0 + length * dz],
                color="black", linewidth=2, alpha=0.85, zorder=3)
        ax.scatter([y0], [z0], color="black", s=25, zorder=4)
        if y0 or z0:
            ax.plot([0.0, y0], [0.0, z0], color="black", linewidth=1, linestyle=":", alpha=0.6, zorder=3)


LID_COMPONENTS = ["Fx", "Fy", "Fz", "NormF", "Tx", "Ty", "Tz", "NormT"]
CUSTOM_TABLE_NAME = "TableForceTorqueSum_perLid.txt"
CUSTOM_VISUALIZATION_NAME = "CustomLidsVisualization.png"


def make_preview_png(step_folder, lines, output_path):
    """Draw rays, colored regions and cubes in the (Y, Z) plane and save it to output_path."""
    data = _read_force_data(step_folder)
    if data is None:
        return output_path

    y = data["y"]
    z = data["z"]
    rays = build_rays(lines)
    half = compute_plot_half_extent(y, z, rays)
    grid, n_regions = build_region_grid(rays, half)
    ids = _lookup_regions(grid, y, z, half)

    try:
        fig, ax = plt.subplots(figsize=(9, 9))
        _draw_yz_frame(ax, half, "Custom Lids - preview (plane Y-Z)")

        palette = plt.cm.tab10 if n_regions <= 10 else plt.cm.tab20
        colors = [palette(i % palette.N) for i in range(n_regions)]
        region_cmap = matplotlib.colors.ListedColormap(colors)
        ax.imshow(
            grid, origin="lower", extent=[-half, half, -half, half], cmap=region_cmap,
            vmin=0.5, vmax=n_regions + 0.5, interpolation="nearest", alpha=0.25, zorder=0,
        )

        _draw_rays(ax, rays, half)

        for index in range(1, n_regions + 1):
            mask = ids == index
            if np.any(mask):
                ax.scatter(y[mask], z[mask], s=50, color=colors[index - 1], edgecolor="black",
                           linewidth=0.4, alpha=0.95, label=f"Lid {index}", zorder=5)

        ax.legend(loc="upper right")
        fig.tight_layout()
        fig.savefig(output_path, dpi=200, bbox_inches="tight")
    finally:
        plt.close("all")
    return output_path


def _safe_table_row(row_name, n_cubes, Fx_sum, Fy_sum, Fz_sum, normF, Tx_sum, Ty_sum, Tz_sum, normT):
    return [
        row_name,
        n_cubes,
        Fx_sum,
        Fy_sum,
        Fz_sum,
        normF,
        Tx_sum,
        Ty_sum,
        Tz_sum,
        normT,
    ]


def _build_folder_name(region_count, counts_by_region):
    name = f"{region_count}Lids"
    parts = [name]
    for index, count in enumerate(counts_by_region, start=1):
        parts.append(f"Lid{index}_{count}Cubes")
    return "_".join(parts)


def _ring_numbers(x, tol=1e-6):
    """Ring index (1-based) per cube and the x position of each ring, as in the standard Lids analysis."""
    unique_x, inverse = np.unique(np.round(x / tol) * tol, return_inverse=True)
    return unique_x, inverse + 1


def _summarize_step(data, region_ids, n_regions):
    """Per (ring, region) sums of forces and torques plus the centroid used to place the sample."""
    unique_x, rings = _ring_numbers(data["x"])
    summary = []
    for ring in np.unique(rings):
        for index in range(n_regions):
            mask = (rings == ring) & (region_ids == index)
            if not np.any(mask):
                continue
            sums = {name: float(data[name][mask].sum()) for name in ("Fx", "Fy", "Fz", "Tx", "Ty", "Tz")}
            sums["NormF"] = math.sqrt(sums["Fx"] ** 2 + sums["Fy"] ** 2 + sums["Fz"] ** 2)
            sums["NormT"] = math.sqrt(sums["Tx"] ** 2 + sums["Ty"] ** 2 + sums["Tz"] ** 2)
            summary.append({
                "ring": int(ring),
                "region": index,
                "n_cubes": int(np.count_nonzero(mask)),
                "sums": sums,
                "position": (
                    float(unique_x[ring - 1]),
                    float(data["y"][mask].mean()),
                    float(data["z"][mask].mean()),
                ),
            })
    return summary


def _padded_limits(values):
    low, high = float(np.min(values)), float(np.max(values))
    if high - low < 1e-9:
        low, high = low - 1e-3, high + 1e-3
    return (low, high)


def plot_custom_lids_component(positions, values, labels, title, savepath, magnet_info,
                               limits, signed_absmax=None):
    """3D + XY/XZ/YZ views of one component summed per (ring, region); saved to savepath."""
    positions = np.asarray(positions, dtype=float)
    values = np.asarray(values, dtype=float)

    if signed_absmax is None:
        vmin, vmax, cmap = float(values.min()), float(values.max()), "hot_r"
    else:
        vmax = signed_absmax if signed_absmax > 0 else 1.0
        vmin, cmap = -vmax, "seismic"

    imax = int(np.argmax(values))
    imin = int(np.argmin(values))
    xlim, ylim, zlim = limits

    try:
        fig = plt.figure(figsize=(20, 4.8))
        gs = fig.add_gridspec(1, 5, width_ratios=[1.35, 1.2, 1.2, 1, 0.05], wspace=0.55)

        ax3d = fig.add_subplot(gs[0, 0], projection="3d")
        sc = ax3d.scatter(positions[:, 0], positions[:, 1], positions[:, 2],
                          c=values, cmap=cmap, vmin=vmin, vmax=vmax, s=100)
        ax3d.scatter(*positions[imax], s=100, marker="^", facecolor="maroon", edgecolor="black", linewidth=1.5)
        ax3d.scatter(*positions[imin], s=100, marker="v", facecolor="navy", edgecolor="black", linewidth=1.5)
        ax3d.set_box_aspect([1, 1, 1])
        ax3d.set_xlim(xlim)
        ax3d.set_ylim(ylim)
        ax3d.set_zlim(zlim)
        ax3d.set_xlabel("x [m]")
        ax3d.set_ylabel("y [m]")
        ax3d.set_zlabel("z [m]")
        legend = ax3d.legend(handles=[
            matplotlib.lines.Line2D([0], [0], marker="^", color="w", markerfacecolor="maroon",
                                    markeredgecolor="black", markersize=9, linestyle="None",
                                    label=f"MAX: {values[imax]:.2f} ({labels[imax]})"),
            matplotlib.lines.Line2D([0], [0], marker="v", color="w", markerfacecolor="navy",
                                    markeredgecolor="black", markersize=9, linestyle="None",
                                    label=f"MIN: {values[imin]:.2f} ({labels[imin]})"),
        ], loc="upper right", frameon=True)
        legend.get_frame().set_alpha(0.9)

        views = [
            (gs[0, 1], 0, 1, xlim, ylim, "x [m]", "y [m]"),
            (gs[0, 2], 0, 2, xlim, zlim, "x [m]", "z [m]"),
            (gs[0, 3], 1, 2, ylim, zlim, "y [m]", "z [m]"),
        ]
        for spec, i, j, xl, yl, xlabel, ylabel in views:
            ax = fig.add_subplot(spec)
            ax.scatter(positions[:, i], positions[:, j], c=values, cmap=cmap, vmin=vmin, vmax=vmax, s=100)
            ax.scatter(positions[imax, i], positions[imax, j], s=100, marker="^", facecolor="maroon", edgecolor="black")
            ax.scatter(positions[imin, i], positions[imin, j], s=100, marker="v", facecolor="navy", edgecolor="black")
            ax.set_aspect("equal")
            ax.set_xlim(xl)
            ax.set_ylim(yl)
            ax.set_xlabel(xlabel)
            ax.set_ylabel(ylabel)

        fig.colorbar(sc, cax=fig.add_subplot(gs[0, 4])).set_label(title)
        fig.suptitle(title + "\n" + f"$\\it{{Magnet:\\ {magnet_info}}}$", fontsize=15, y=0.975)
        fig.tight_layout(rect=[0, 0, 0.97, 0.94])
        fig.savefig(savepath, dpi=300, bbox_inches="tight")
    finally:
        plt.close("all")


def run_custom_lids_analysis(base_folder, magnet_info, config_path):
    """Generate every custom-lid output inside <Step>/<N>Lids_.../ (nothing is written to the Step root)."""
    if not config_path or not os.path.exists(config_path):
        return []

    lines = load_custom_lid_config(config_path)
    rays = build_rays(lines)
    if not rays:
        return []

    studies = []
    for step_folder in _iter_step_folders(base_folder):
        data = _read_force_data(step_folder)
        if data is None:
            continue

        half = compute_plot_half_extent(data["y"], data["z"], rays)
        grid, n_regions = build_region_grid(rays, half)
        region_ids = _lookup_regions(grid, data["y"], data["z"], half) - 1
        counts = [int(np.count_nonzero(region_ids == index)) for index in range(n_regions)]
        if not any(counts):
            continue

        studies.append({
            "folder": step_folder,
            "data": data,
            "region_ids": region_ids,
            "n_regions": n_regions,
            "counts": counts,
            "summary": _summarize_step(data, region_ids, n_regions),
        })

    if not studies:
        return []

    # Fixed scales across steps so plots are comparable, as in the standard Lids analysis
    all_rows = [row for study in studies for row in study["summary"]]
    absmax = {
        name: max(abs(row["sums"][name]) for row in all_rows)
        for name in ("Fx", "Fy", "Fz", "Tx", "Ty", "Tz")
    }
    limits = tuple(
        _padded_limits(np.concatenate([study["data"][axis] for study in studies]))
        for axis in ("x", "y", "z")
    )

    processed = []
    for study in studies:
        step_folder = study["folder"]
        step_name = os.path.basename(step_folder)
        folder_name = _build_folder_name(study["n_regions"], study["counts"])
        target_dir = os.path.join(step_folder, folder_name)
        os.makedirs(target_dir, exist_ok=True)

        table_rows = []
        for row in study["summary"]:
            sums = row["sums"]
            table_rows.append(_safe_table_row(
                f"Ring{row['ring']}_Lid {row['region'] + 1}", row["n_cubes"],
                sums["Fx"], sums["Fy"], sums["Fz"], sums["NormF"],
                sums["Tx"], sums["Ty"], sums["Tz"], sums["NormT"],
            ))

        summary_path = os.path.join(target_dir, CUSTOM_TABLE_NAME)
        with open(summary_path, "w", encoding="utf-8") as handle:
            handle.write("Ring_Lid\tN_cubes\tFx_sum\tFy_sum\tFz_sum\tnormF\tTx_sum\tTy_sum\tTz_sum\tnormT\n")
            for table_row in table_rows:
                handle.write("\t".join(str(value) for value in table_row) + "\n")

        for index in range(study["n_regions"]):
            mask = study["region_ids"] == index
            if np.any(mask):
                np.savetxt(os.path.join(target_dir, f"Lid{index + 1}.txt"),
                           study["data"]["data"][mask], delimiter="\t", fmt="%.15g")

        positions = [row["position"] for row in study["summary"]]
        labels = [f"Ring{row['ring']}_Lid {row['region'] + 1}" for row in study["summary"]]
        for component in LID_COMPONENTS:
            plot_custom_lids_component(
                positions,
                [row["sums"][component] for row in study["summary"]],
                labels,
                f"{component} Lids",
                os.path.join(target_dir, f"{step_name}_{component}_Lids.png"),
                magnet_info,
                limits,
                signed_absmax=None if component.startswith("Norm") else absmax[component],
            )

        preview_path = os.path.join(target_dir, CUSTOM_VISUALIZATION_NAME)
        make_preview_png(step_folder, lines, output_path=preview_path)
        processed.append({
            "step": step_name,
            "folder": folder_name,
            "path": target_dir,
            "preview": preview_path,
            "table": summary_path,
        })

    return processed